CREATE TABLE Game (
  id BIGSERIAL NOT NULL,
  score INTEGER NULL,
  boardWords JSONB NULL,
  lastPlay TIMESTAMPTZ NULL,
  createdBy VARCHAR(80) NULL,
  createdDate TIMESTAMPTZ NULL,
  modifiedBy VARCHAR(80) NULL,
  modifiedDate TIMESTAMPTZ NULL,
  PRIMARY KEY (id)
);

CREATE TABLE Word (
  id BIGSERIAL NOT NULL,
  game_Id BIGINT NOT NULL,
  word VARCHAR(25) NULL,
  score INTEGER NULL,
  createdBy VARCHAR(80) NULL,
  createdDate TIMESTAMPTZ NULL,
  modifiedBy VARCHAR(80) NULL,
  modifiedDate TIMESTAMPTZ NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_Word_Game FOREIGN KEY (game_Id) REFERENCES Game (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Game_AUD (
  id BIGINT NOT NULL,
  REV INTEGER NOT NULL,
  REVTYPE SMALLINT NULL,
  score INTEGER NULL,
  boardWords JSONB NULL,
  lastPlay TIMESTAMPTZ NULL,
  createdBy VARCHAR(80) NULL,
  createdDate TIMESTAMPTZ NULL,
  modifiedBy VARCHAR(80) NULL,
  modifiedDate TIMESTAMPTZ NULL,
  PRIMARY KEY (id, REV)
);

CREATE TABLE Word_AUD (
  id BIGINT NOT NULL,
  REV INTEGER NOT NULL,
  REVTYPE SMALLINT NULL,
  game_Id BIGINT NOT NULL,
  word VARCHAR(25) NULL,
  score INTEGER NULL,
  createdBy VARCHAR(80) NULL,
  createdDate TIMESTAMPTZ NULL,
  modifiedBy VARCHAR(80) NULL,
  modifiedDate TIMESTAMPTZ NULL,
  PRIMARY KEY (id, REV)
);
